### ISSUE TITLE
Add CheckNull attribute testing

### ISSUE THREAD

**Issue by damy90** [ivaylokenov/MyTested.WebApi#226]

**Comment by ivaylokenov** [comment]
Can you give more information and source code example? What is CheckNull attribute? I can't find such attribute in WebApi source code: https://aspnetwebstack.codeplex.com/SourceControl/latest

You can do the following currently if such attribute exists:

```c#
MyWebApi
    .Controller<WebApiController>()
    .Calling(c => c.SomeAction())
    .ShouldHave()
    .ActionAttributes(attributes => attributes
        .ContainingAttributeOfType<CheckNullAttribute>());
```

**Comment by damy90** [comment]
It turned out to be a custom ActionFilterAttribute. Thanks for the help.

**Comment by damy90** [comment]
It turned out to be a custom ActionFilterAttribute. Thanks for the help.
