### ISSUE TITLE
Calculate integration tests response time

### ISSUE THREAD

**Issue by tdbgautham** [ivaylokenov/MyTested.WebApi#229]
We like to capture the response time of our API call. Do we have possibility to include response time ?

**Comment by ivaylokenov** [comment]
@tdbgautham  With the current version of the library you cannot, but capturing response time can be an interesting addition to the library. However, I have some concerns:

 - If the tests have mocked objects, for example database layer mock up, the response time in the unit tests will be quite different from the actual response time when using real database
 - The delepment/build machine where the tests are run may be quite different in specifications compared to the actual server, on which the API will be hosted, and the actual response time results may vary

**Comment by tdbgautham** [comment]
@ivaylokenov Here is my suggesions,

   1st Concern-> we can compare Response time for Mocked DB vs Real DB in Unit test.Even though the results may vary, Let it be a added feature which will be interesting to measure average response time to add over Assertion.

   2nd Concern -> let the response time result may vary , but it will have its average measurement based on the servers. So a tester can give his average measurement of calculation for Response time.
  
  3rd Concern -> of-course, there will be Caching & optimization in Web API, But the web api tester is relying only on final Response of an API in unit testing component. The intention here is to capture average response time & assert it with expected value.

this will be helpful . Thanks for this library, which is really helpful . Response time assertion which will boost up this library.

**Comment by ivaylokenov** [comment]
@tdbgautham 
Sure, I will think of a way to add it as a feature. IN your opinion should response time calculation be only added in the Integration Server tests or on the Controller tests too?

**Comment by tdbgautham** [comment]
@ivaylokenov  It should be in the Integration Server test.

**Comment by ivaylokenov** [comment]
@tdbgautham My thoughts exactly. Constroller tests are too separated from the API call and the response time will not bring quite a lot of value.

**Comment by tdbgautham** [comment]
@ivaylokenov  yes :+1:

**Comment by ivaylokenov** [comment]
@tdbgautham Implemented. Just update the package to version 1.1.7. You can see more information here: https://github.com/ivaylokenov/MyTested.WebApi/tree/master/documentation#response-time There is also an AndProvideTheResponseTime method which returns directly the TimeSpan value.
