### ISSUE TITLE
How to test User.Identity.GetUserId<int>() in an Action?

### ISSUE THREAD

**Issue by foresightyj** [ivaylokenov/MyTested.WebApi#241]
I know this is probably not supported but I am asking for your views on this.

My action looks like:

        [Route("~/friends")]
        [Authorize]
        [HttpGet]
        public IHttpActionResult GetFriends()
        {
            var authenticatedUserId = User.Identity.GetUserId<int>();
            return Ok(_userService.GetFriendsOfUser(authenticatedUserId));
        }

So an authenicated user can only read his/her friends, not other users' friends.

With `WithAuthenticatedUser`, I can only fake `UserName` and `AuthenticationType` but in my case, `UserName` is not necessarily unique so it is useless to me.

It is currently impossible to fake `User.Identity.GetUserId` so as to make this test pass. But I found it compelling to read UserIds. What do you suggest for such test cases? Thanks.

**Comment by ivaylokenov** [comment]
@foresightyj The user Id is just a claim, so I can easily add a method `WithClaim` where you can add `ClaimTypes.NameIdentifier` with value and the `GetUserId<int>()` method will return it for you making the test pass. I will add it during the weekend. For now you can make the following workaround to make the test pass:

Controller
```c#
        public IHttpActionResult Get()
        {
            var id = this.User.Identity.GetUserId<int>();
            return Ok(id);
        }
```

Test
```c#
        [TestMethod]
        public void Get()
        {
            var controllerBuilder = MyWebApi
                .Controller<ValuesController>();

            var mockedController = controllerBuilder.AndProvideTheController();
            mockedController.User = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.NameIdentifier, "1") }));

            controllerBuilder
                .Calling(c => c.Get())
                .ShouldReturn()
                .Ok()
                .WithResponseModel(1);
        }
```

If you have other requests, please let me know!

**Comment by foresightyj** [comment]
Thanks a lot for the prompt reply! Can't wait to use the new feature.

**Comment by ivaylokenov** [comment]
@foresightyj You can update to version 1.2. It adds two options to the user builder - `WithIdentifier` and `WithClaim`, which will allow you to test an action with `GetUserId` method call.

**Comment by foresightyj** [comment]
Tried it and it worked really well. Thanks a lot!
