### ISSUE TITLE
Integration test doesn't respect RoutePrefix and Route

### ISSUE THREAD

**Issue by foresightyj** [ivaylokenov/MyTested.WebApi#246]
Here is what I've done to a newly created Web API project with scaffolding:

First, comment out the following line in `Application_Start` in Global.asax.cs:

    //GlobalConfiguration.Configure(WebApiConfig.Register);

Then add Owin-required `Startup.cs` like this (note **v1** is added to the middle of `routeTemplate`):

    [assembly: OwinStartup(typeof(Startup))]

    namespace SelfHostWebApi2
    {
        public class Startup
        {
            // This code configures Web API. The Startup class is specified as a type parameter in the
            // WebApp.Start method.
            public void Configuration(IAppBuilder appBuilder)
            {
                // Configure Web API for self-host. 
                var config = new HttpConfiguration();

                config.Routes.MapHttpRoute(
                    name: "DefaultApi",
                    routeTemplate: "api/v1/{controller}/{id}",
                    defaults: new { id = RouteParameter.Optional }
                );

                appBuilder.UseWebApi(config);
            }
        }
    }

In ValuesController.cs, I changed these two places for testing purposes:

    [RoutePrefix("api/v2")]
    public class ValuesController : ApiController
 
    // GET api/values/5 
    [Route("getvalues/{id}")]
    public int Get(int id)
    {
        return id;
    }

In the unit test, I have two test cases: 

    [TestMethod]
    public void TestMethod1()
    {
        MyWebApi
            .Server()
            .Working<Startup>(host: "https://localhost", port: 9876) //
            .WithHttpRequestMessage(
                request => request
                    .WithMethod(HttpMethod.Get)
                    .WithRequestUri("api/v1/values/5"))
            .ShouldReturnHttpResponseMessage()
            .WithStatusCode(HttpStatusCode.OK)
            .WithResponseModelOfType<int>()
            .Passing(m =>
            {
                Assert.AreEqual(5, m);
            });
    }

    [TestMethod]
    public void TestMethod2()
    {
        MyWebApi
            .Server()
            .Working<Startup>(host: "https://localhost", port: 9876) //
            .WithHttpRequestMessage(
                request => request
                    .WithMethod(HttpMethod.Get)
                    .WithRequestUri("api/v2/getvalues/5"))
            .ShouldReturnHttpResponseMessage()
            .WithStatusCode(HttpStatusCode.OK)
            .WithResponseModelOfType<int>()
            .Passing(m =>
            {
                Assert.AreEqual(5, m);
            });
    }

`TestMethod1` is success and `TestMethod2` **failed**. The error message is
> MyTested.WebApi.Exceptions.HttpResponseMessageAssertionException: When testing ServerHttpMessageHandler expected HTTP response message result status code to be 200 (OK), but instead received 404 (NotFound).

![image](https://cloud.githubusercontent.com/assets/1296736/12286653/15c839d2-ba01-11e5-81c4-c6f11b90bd5a.png)

However, according to the RoutePrefix and Route Attributes, `TestMethod` should fail instead.

For the purpose of replicating my errors, I attached the whole project files here. Thanks.

**Oh, BTW, is there any better way to integrate-test the default mixed mvc + web api project? I had to manually add owin's Startup.cs and disable the default web api configuration like what I did above.**

[SelfHostWebApi2.zip](https://github.com/ivaylokenov/MyTested.WebApi/files/88443/SelfHostWebApi2.zip)

**Comment by ivaylokenov** [comment]
@foresightyj  You are missing 'config.MapHttpAttributeRoutes();' after initialization of the `HttpConfiguration` in your `Startup` class. Add it and the second `TestMethod2` will pass. 

Otherwise you can integrate-test the default project with HTTP server configuration instead of OWIN:

```c#
    [TestClass]
    public class MyUnitTests
    {
        private IServerBuilder server;

        [TestInitialize]
        public void Init()
        {
            server = MyWebApi
                .IsRegisteredWith(WebApiConfig.Register)
                .AndStartsServer();
        }

        [TestMethod]
        public void TestRoute()
        {
            server
                .WithHttpRequestMessage(
                    request => request
                        .WithMethod(HttpMethod.Get)
                        .WithRequestUri("api/v2/getvalues/5"))
                .ShouldReturnHttpResponseMessage()
                .WithStatusCode(HttpStatusCode.OK)
                .WithResponseModelOfType<int>()
                .Passing(m =>
                {
                    Assert.AreEqual(5, m);
                });
        }

        // More unit tests on server instance

        [TestCleanup]
        public void Clean()
        {
            MyWebApi
                .Server()
                .Stops();
        }
    }
```

Can you confirm it is working correctly, so I can close the issue?

**Comment by foresightyj** [comment]
Sorry, that is totally my ignorance. Please close it. Thanks.

I didn't quite get what *HTTP server* was doing while reading the documentation. I will try that.

**Comment by ivaylokenov** [comment]
@foresightyj  HTTP server is using the default Web API class `HttpServer` to run the integration tests. It just need proper `HttpConfiguration' to process requests. The OWIN integration tests use the `Startup.cs` class to process the requests. Since the Web API framework has two ways to start - in IIS and self-hosted, I had to support both ways. It may be confusing at first, but I tried to explain it as much as I could in the documentation.

**Comment by foresightyj** [comment]
I tried the `IServerBuilder`'s way of integration test. It works well with the default web api project scaffold in visual studio.

But another problem arises quickly. I also used ASP.NET Identity. So my project already used OWIN and in `Startup.cs` there are only ASP.NET Identity-related OWIN-middlewares. One of the major purposes of my integration test is to test the authentication and authorization.

I found no way to insert the OWIN configuration to the existing `IServerBuilder` instance. Is it even possible?

**Comment by ivaylokenov** [comment]
@foresightyj Unfortunately, there is no way to start both servers. You need to use the `Startup.cs` way of integration testing. Here is a sample for the OWIN identity:

https://github.com/ivaylokenov/MyTested.WebApi/blob/master/samples/Books%20Web%20API/Books.Tests/ApiTests/IntegrationTests/BooksControllerIntegrationTests.cs

**Comment by foresightyj** [comment]
Thanks for your help. I move web api into OWIN instead and it works like a charm.

I added a configuration value `UseOwinWebAPI=false` to Web.config of the web api project and `UseOwinWebAPI=true` to the unit test project. I will only call `appBuilder.UseWebApi` if this value is true.

**Comment by ivaylokenov** [comment]
You are welcome. I am glad I could help.
