### ISSUE TITLE
Cannot pass null into WithResolvedDependencyFor

### ISSUE THREAD

**Issue by foresightyj** [ivaylokenov/MyTested.WebApi#253]
My controller's constructor looks like:

        public AccountController(IUserCommandService userCommandService,
            IUserQueryService userQueryService,
            IAccountCommandService accountCommandService)

I am testing an action called `Register`, which only uses `IUserCommandService`, so in the unit test, to save some mocking/stubbing, I'd like to pass nulls to `IUserQueryService` and `IAccountCommandService`. 

            MyWebApi
             .Controller<API.Areas.ApiV1.Controllers.AccountController>()
             .WithResolvedDependencyFor(_userCommandService)
             .WithResolvedDependencyFor<IUserQueryService>(null)
             .WithResolvedDependencyFor<IAccountCommandService>(null)
             .CallingAsync(c => c.Register(model))
             .ShouldReturn()
             .Ok();

But currently MyTested.WebAPI doesn't support that. The `WithResolvedDependencyFor`'s source code is:

        public IAndControllerBuilder<TController> WithResolvedDependencyFor<TDependency>(TDependency dependency)
        {
            var typeOfDependency = dependency.GetType();
            if (this.aggregatedDependencies.ContainsKey(typeOfDependency))
            {
                throw new InvalidOperationException(string.Format(
                    "Dependency {0} is already registered for {1} controller.",
                    typeOfDependency.ToFriendlyTypeName(),
                    typeof(TController).ToFriendlyTypeName()));
            }

            this.aggregatedDependencies.Add(typeOfDependency, dependency);
            this.controller = null;
            return this;
        }

So it will try to call `GetType` on the passed-in instance, which will result in a NullReferenceException.

Is it normal to pass nulls to parameters which you know you are not using in the test?

**Comment by ivaylokenov** [comment]
@foresightyj Hi, I believe you have a point. Will upload a new version fixing this issue in one or two days.

**Comment by ivaylokenov** [comment]
@foresightyj Implemented in version 1.2.2. You can update the package. Null dependencies are now allowed.
