### ISSUE TITLE
Route Testing: ignoring parameters

### ISSUE THREAD

**Issue by paulduran** [ivaylokenov/MyTested.WebApi#258]
Hi,

I was wondering if there is an option to tell the route tester to ignore the parameters specified.

We have some WebApi routes that use the OData extensions for data filtering. An example signature is:

```
public IEnumerable<MyModel> GetMyItems(ODataQueryOptions<MyDomainObject> query)
{
}
```

When testing, I'm not sure how to construct an ODataQueryOptions that would match the expected value - I'm not particularly concerned with validating this - moreso, just validating that the route is correctly hitting that controller.

Is there a way that I can specify to ignore the parameters passed into the controller action?

**Comment by ivaylokenov** [comment]
@paulduran Currently there is no such option but I can add methods for testing with strings only the controllers and the actions for example:

```c#
MyWebApi
    .Routes()
    .ShouldMap("api/WebApiController/SomeAction")
    .ToController("WebApi")
    .ToAction("SomeAction");
```

Will that work for you?

Additionally, I can make the following to ignore the route values (currently it does not)

```c#
MyWebApi
    .Routes()
    .ShouldMap("api/WebApiController/GetMyItems")
    .To<WebApiController>(c => c.GetMyItems(With.Any<ODataQueryOptions<MyDomainObject>>()));
```

Will add these in the next couple of days and update the package.

**Comment by paulduran** [comment]
Thanks, either of those solutions would be fine!

**Comment by ivaylokenov** [comment]
@paulduran The features you requested are now implemented. You can update the package to version 1.2.3.

**Comment by paulduran** [comment]
@ivaylokenov Many thanks for that! Those changes work a treat for the tests where I need to ignore the parameters.

version 1.2.3 appears to have broken something else though. I'll raise a separate issue for that.
