### ISSUE TITLE
IOkTestBuilder Ok() fails with async controller actions

### ISSUE THREAD

**Issue by IvayloGoranov** [ivaylokenov/MyTested.WebApi#268]
If the controller action is asynchroneous, the following code in a test method will result in test fail with message "OkNegotiatedContentResult was expected, but instead Task<OkNegotiatedContentResult> was returned":

MyWebApi
                .Controller<ProjectsController>()
                .WithResolvedDependencyFor(TestObjectFactory.GetProjectsService())
                .Calling(c => c.Get())
                .ShouldReturn()
                .Ok()
                .WithResponseModelOfType<List<SoftwareProjectDetailsResponseModel>>();

Is there a way to use the testing framework to test async actions in the same sense,?

**Comment by ivaylokenov** [comment]
@IvayloGoranov Yes, you have `.CallingAsync` method: 

https://github.com/ivaylokenov/MyTested.WebApi/tree/master/documentation#calling-actions

**Comment by IvayloGoranov** [comment]
Yes, works like a charm :)
Thanks a lot.
