### ISSUE TITLE
Using with StructureMap IoC

### ISSUE THREAD

**Issue by thisispaulsmith** [ivaylokenov/MyTested.WebApi#271]
Are there any examples of using MyTested with StructureMap?

As StrutureMap is configured via the `WebHostBuilder` this causes an issue

```
The type initializer for 'MyTested.AspNetCore.Mvc.MyMvc' threw an exception.
No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[StructureMap.Registry]' has been registered.
```

**Comment by ivaylokenov** [comment]
@thisispaulsmith Can you give a sample code with your registration of Structure Map? I believe this will do the job:

https://github.com/ivaylokenov/MyTested.WebApi/tree/master/documentation#custom-dependency-resolver

**Comment by thisispaulsmith** [comment]
@ivaylokenov apologies I've posted this in the wrong repo! It should have been in  aspnetcore

**Comment by ivaylokenov** [comment]
@thisispaulsmith Yes, that would be great.
