### ISSUE TITLE
ExceptionFilterAttribute handling

### ISSUE THREAD

**Issue by roman-makarov-wa** [ivaylokenov/MyTested.WebApi#274]
Hi.
I have a controller attribute derived from System.Web.Http.Filters.ExceptionFilterAttribute.
This attribute catches exceptions and returns BadRequest/InternalServerError responses.

But when I testing controller with MyTested.WebApi exception is thrown and execution breaking before entering the Attribute and  there is no response from webapi actually.
Are there any ideas how to test such scenarios?

Thank you

`public class WebApiExceptionFilterAttribute : ExceptionFilterAttribute
    {
        public override void OnException(HttpActionExecutedContext context)
        {
            string requestInfo = $"{context.Request.Method} {context.Request.RequestUri.AbsoluteUri}";
            if (context.Exception is HttpRequestException
                || context.Exception is ArgumentException
                || context.Exception is InvalidStateException)
            {
                context.Response = new HttpResponseMessage
                {
                    Content = new StringContent($"{context.Exception.Message} (source: {requestInfo})", System.Text.Encoding.UTF8, "text/plain"),
                    StatusCode = HttpStatusCode.BadRequest
                };

                return;
            }

            var httpResponseException = context.Exception as HttpResponseException;
            if (httpResponseException != null && httpResponseException.Response != null)
            {
                context.Response = httpResponseException.Response;
                return;
            }

            string errorDetails = $"{requestInfo} {context.Exception.Message}";
            context.Response = context.Request.CreateResponse(HttpStatusCode.InternalServerError, errorDetails);
        }
    }`

**Comment by roman-makarov-wa** [comment]
Found the solution.

MyWebApi
                .Server()
                .Working()
                .WithHttpRequestMessage(
                    request => request
                        .WithJsonContent(JsonConvert.SerializeObject(model))
                        .WithMethod(HttpMethod.Put)
                        .WithRequestUri($"{CONTROLLER_BASE_URL}"))
                .ShouldReturnHttpResponseMessage()
                .WithStatusCode(HttpStatusCode.BadRequest);

**Comment by ivaylokenov** [comment]
The above code is the correct solution. 

`MyWebApi.Controller` runs a unit test - only the controller action code is executed.

`MyWebApi.Server` runs an integration test - runs the whole pipeline.
