### ISSUE TITLE
.NET Core 1.x or 2 support missing

### ISSUE THREAD

**Issue by Boriszn** [ivaylokenov/MyTested.WebApi#278]
Hi, 

This solution looks pretty nice and useful. But, unfortunately it doesn't work in .net core projects (Please correct me if I wrong). 
Do you have plan to add  .net core (.net standard) support ?

**Comment by bartlannoeye** [comment]
Core 1.x is supported in https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc, still waiting for a Core 2 version.

**Comment by ivaylokenov** [comment]
Yes, you should use https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc for .NET Core.
