### ISSUE TITLE
Could not install package 'MyTested.WebApi2 2.0.7

### ISSUE THREAD

**Issue by Calabonga** [ivaylokenov/MyTested.WebApi#279]
Cannot install package:

`Could not install package 'MyTested.WebApi2 2.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by ivaylokenov** [comment]
Hi, @Calabonga. Package MyTested.WebApi2 is forked from this repository and it is not maintained by me and my contribution team: https://github.com/vip32/MyTested.WebApi

You may try the version we just published in NuGet - https://www.nuget.org/packages/MyTested.WebApi and let us know if it suits your needs.
