### ISSUE TITLE
Issue with custom authorization attribute

### ISSUE THREAD

**Issue by Texas-E** [ivaylokenov/MyTested.WebApi#280]
I have an authorization attribute that inherits from MVC.AuthorizeAttribute, but I addd the OnAuthorization method to catch HttpActionContext for my webAPI so that I don't have to use two separate authorization classes in my app. The authorization works, no issues. However, I'm unable to use the .RestrictingForAuthorizedRequests() method, and am forced to use the .ContainingAttributeofType<T>() method, which is fine I suppose. 

If I have a controller like this:

`    
[RoutePrefix("api/notifications")]
    [myCustomAuthorize(Roles = "admin")]
    public class NotificationsController : ApiController
    {
        private readonly IMediator _mediator;
        public NotificationsController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [HttpGet]
        [Route("active")]
        public async Task<List<NotificationModel>> Active()
        {
               // Does work
        }
    }
`

How do I get this to pass?

`  
     [Fact]
        public void Active_notAdmin_Returns()
        {
            // Arrange
            IPrincipal principal = TestClaimsPrincipal.TestAdminClaimsPrincipal("notAnAdmin");

            // Act
            var test = MyWebApi.Controller<NotificationsController>()
                .WithResolvedDependencies(_mediator.Object)
                .WithSetup(x => { x.User = principal; });

            // Assert
            test.ShouldHave().Attributes(attr => attr.ContainingAttributeOfType<myCustomAuthorize>());
            test.CallingAsync(x => x.Active()).ShouldReturn().Unauthorized();
        }
`

Considering 
` test.CallingAsync(x => x.Active()).ShouldReturn().Unauthorized();`

currently returns default value.

Muchas gracias!

**Comment by Texas-E** [comment]
I have also tried 

`
            // Arrange
            IPrincipal principal = TestClaimsPrincipal.TestAdminClaimsPrincipal("notAnAdmin");

            HttpActionContext mockActionContext = new HttpActionContext()
            {
                ControllerContext = new HttpControllerContext()
                {
                    RequestContext = new HttpRequestContext() { Principal = principal }
                },
            };

            var controller = MyWebApi.Controller<NotificationsController>()
                .WithResolvedDependencies(_mediator.Object)
                .WithSetup(x =>
                {
                    x.ActionContext = mockActionContext;
                    x.User = principal;
                });

            // Act

            // Assert
            controller.Calling(x => x.Active()).ShouldReturn().Unauthorized();
`
And I get 
>When calling Active action in NotificationsController expected action result to be UnauthorizedResult, but instead received Task<List<NotificationModel>>

**Comment by ivaylokenov** [comment]
Hi,

Thank you for using the library!

The `MyWebApi.Controller` method runs a unit test, so the authorization filter is not run before the actual call.

```.RestrictingForAuthorizedRequests()``` checks only for the default AuthorizeAttribute.

This call is enough to validate the action is decorated correctly:
```c#
test.ShouldHave().Attributes(attr => attr.ContainingAttributeOfType<myCustomAuthorize>());
```

If you want to run the whole pipeline with filters, actions and so on, you need to use integration tests, which are started by ```MyWebApi.Server()```. You may check the documentation for examples.
